### ISSUE TITLE
Reference to AppViewListener is wrong [Alpha 46]

### ISSUE THREAD

**Issue by binarious** [rangle/batarangle#78] opened 2015-11-27 10:22 UTC
Inside the [example app](https://github.com/rangle/batarangle/blob/master/example-apps/todo-mvc-example/source/app.ts#L10) you include the `AppViewListener` this way:
```typescript
import {AppViewListener} from 'angular2/src/core/linker/view_listener.js';
```

This results in `Cannot find module angular2/src/core/linker/view_listener.js` for me.

**Comment by bertrandk** [comment] 2015-11-27 19:04
That's odd, while things have moved around significantly with alpha 46, [this file seems to be where it was in 45](https://github.com/angular/angular/blob/2.0.0-build.4616347.js/src/core/linker/view_listener.js). There are probably other issues as well with 46. Probably only worth looking into 46 support with #70 unless there is something straight forward we can do. (Maybe even push it back to [beta](https://github.com/angular/angular/milestones/beta-00) and let core settle a bit.)

Thoughts @vanessayuenn?

**Comment by vanessayuenn** [comment] 2015-12-01 15:06
It probably doesn't have anything to do with alpha 45 vs 46. 

@binarious, where did you see this error? If it's from the typescript compiler, the sample app actually doesn't require compiling manually - just `npm install` then `http-server` to serve it up will suffice. The `system.js` and `config.js` included in `index.html` will let the app know where to look for the dependencies properly. While this is not a blocker, it should still be addressed in the near future. 

Let me know if this resolves the issue!

**Comment by binarious** [comment] 2015-12-09 10:17
@vanessayuenn Yes, the error is thrown by the typescript compiler. When I ignore it, the Angular2 tab in Chrome doesn't display anything besides the search bar.

**Comment by StrangeCargo74** [comment] 2015-12-14 17:59
I ran into this, and googled my way here. Maybe more will follow. 

I am trying to use batarangle in an app that is compiled from typescript. Using the import in the original post breaks the compile. It's not a bug.

When more skill arrives I'll work out how to get the typings right for me to import the AppViewListene and DebugElementViewListener in a way that the compiler likes.

**Comment by artichokes** [comment] 2015-12-24 02:22
The correct imports for Angular 2.0 Beta 0 are:
```
import {bind} from 'angular2/core';
import {bootstrap, inspectNativeElement} from 'angular2/platform/browser';
import {AppViewListener} from 'angular2/src/core/linker/view_listener';
import {DebugElementViewListener} from 'angular2/platform/common_dom';
```

**Comment by SethDavenport** [comment] 2015-12-30 21:53
PR #87 updates the README.md with the correct imports.  The example app still needs to be ported to beta-0 though.

**Comment by SethDavenport** [comment] 2016-01-04 19:39
PR #88 updates the app to beta and corrects the imports.

**Closed by SethDavenport** 2016-01-04 19:39 UTC
Labels: bug, question
