### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by hermanfransen** [rangle/batarangle#283] opened 2016-04-08 09:20 UTC
Trying to install:

Batarangle-445.crx
on Chrome 49.0.2623.110 (64-bit)

I drop the file in the extension tab. It says it's installed and Batarangle button appear next to url input. But when I click on the Batarangle button, I get the message "File not found" ERR_FILE_NOT_FOUND.

**Comment by mobinni** [comment] 2016-04-08 10:43
I'm able to reproduce that error:
![](http://i.imgur.com/HSqHOfG.png)

Seems to be an issue with the browser-action. Maybe the build doesn't include popup.html?

**Comment by sumitarora** [comment] 2016-04-08 12:32
@hermanfransen @mobinni Thanks for checking added fix https://github.com/rangle/batarangle/pull/284 should be merged soon.

**Closed** 2016-04-08 14:04 UTC
Labels: bug
